### ISSUE TITLE
Creeper Overhaul Compatibility

### ISSUE THREAD

**Issue by ardissaps** [Ladysnake/Creeper-Spores#33] opened 2022-06-27 13:44 UTC
Is it compatible with [Creeper Overhaul Mods](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)(not the resourcepack version)?

**Comment by Pyrofab** [comment] 2022-06-27 13:45
Would you mind trying it and reporting back ? Creeperlings should use the creeper texture, but I do not know how they will react to alternative models.

**Comment by ardissaps** [comment] 2022-06-27 16:38
Their creeper is different from each biome, not only the model but also change behaviour, I post wrong link, what I should link is not the resource pack version but mod version here : [Creeper Overhaul Mods](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul) (I will also edit earlier post)

**Comment by Pyrofab** [comment] 2022-08-31 21:12
Closing this as duplicate of #28

**Closed as completed by Pyrofab** 2022-08-31 21:12 UTC
